version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=root
      - DB_PASSWORD=mariadb
      - DB_HOST=mariadb
      - DB_NAME=fastapi
      - RABBIT_USER=root
      - RABBIT_PASSWORD=root
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - mariadb

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb  # Ajuste a senha conforme necessário
      MYSQL_DATABASE: fastapi  # Ajuste o nome do banco de dados conforme necessário
    ports:
      - "33306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  rabbitmq_data:
